# Generated by Django 5.1.6 on 2025-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movielike'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
