# Generated by Django 5.2.4 on 2025-08-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extra/')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='movieapp.actor')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='movieapp.movie')),
            ],
        ),
    ]
