# Generated by Django 5.2.4 on 2025-08-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_actor_description_actor_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='poster',
        ),
    ]
