# Generated by Django 5.2.4 on 2025-08-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_rename_image_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
